### ISSUE TITLE
Bug in example benchmark.yml

### ISSUE THREAD

**Issue by erkkikeranen** [fcsonline/drill#78]
Using version 0.6.0

Following the example: 

When running the node express server 

`DELAY_MS=100 node server.js`

and running 

`drill --benchmark benchmark.yml --stats`

fails:

```
Threads 1
Iterations 3
Rampup 2
Base URL http://localhost:9000

Fetch comments            http://localhost:9000/api/comments.json 404 Not Found 103ms
Fetch sub comments        http://localhost:9000/api/subcomments.json 404 Not Found 106ms
Fetch users               http://localhost:9000/api/users.json 200 OK 104ms
Fetch organizations       http://localhost:9000/api/organizations 200 OK 104ms
Fetch account             http://localhost:9000/api/account 200 OK 105ms
thread '<unnamed>' panicked at 'Unknown 'foo.body.manager_id' variable!', /Users/erkki.keranen/.cargo/registry/src/github.com-1ecc6299db9ec823/drill-0.6.0/src/interpolator.rs:38:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'arrrgh', /Users/erkki.keranen/.cargo/registry/src/github.com-1ecc6299db9ec823/drill-0.6.0/src/benchmark.rs:88:14

```

Solution:

remove `.body` from interpolation variables in benchmark.yml

i.e. `foo.body.something -> foo.something`

benchmark runs.

Is pull request welcome?
:)

**Comment by erkkikeranen** [comment]
never mind, 

or actually it seems that the yaml format has changed and examples are not compatible with the 0.6.0 release from the master branch. 

my bad!

**Comment by fcsonline** [comment]
Yep! They changed since we introduced header support!
