### ISSUE TITLE
Body will be empty when executing PATCH methods.

### ISSUE THREAD

**Issue by yoshihitoh** [fcsonline/drill#80]
First, thank you for this great load testing tool!
I like the `assign` feature, which makes drill and its template really flexible.

I noticed that the current version of drill does not send `body` if I use `PATCH` method.
Tested with this template.

<details><summary>test.yaml</summary>
<p>

```yaml
---
concurrency: max
iterations: 1

plan:
    - name: Assign access token
      assign:
        key: access_token
        value: MY-ACCESS-TOKEN-HERE

    - name: Do something with access token
      request:
        url: http://127.0.0.1:3000/items/{{ item }}
        method: PATCH
        body: '{"params": {"name": "NAME"} }'
        headers:
          Authorization: Bearer {{ access_token }}
          Content-Type: application/json
      with_items:
        - "ITEM-ID-1"
        - "ITEM-ID-2"
```
</p>
</details>

Used server for debugging.

<details><summary>main.py</summary>
<p>

```python
from http.server import BaseHTTPRequestHandler, HTTPServer
import logging


class Handler(BaseHTTPRequestHandler):
    def _set_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_PATCH(self):
        content_length = int(self.headers['Content-Length']) # <--- Gets the size of data
        post_data = self.rfile.read(content_length) # <--- Gets the data itself
        logging.info("PATCH request,\nPath: %s\nHeaders:\n%s\n\nBody:\n%s\n",
                     str(self.path), str(self.headers), post_data.decode('utf-8'))

        self._set_response()
        self.wfile.write("PATCH request for {}".format(self.path).encode('utf-8'))


def run(server_class=HTTPServer, handler_class=Handler, port=3000):
    logging.basicConfig(level=logging.INFO)
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    logging.info('Starting httpd...\n')
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()
    logging.info('Stopping httpd...\n')


if __name__ == '__main__':
        run()
```
</p>
</details>

After running this debugging server, I executed drill with the above template.
But the server didn't show request body and its content-length, so the server will raise an exception.

```bash
# Run server
$ python3 main.py
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52838)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "main.py", line 17, in do_PATCH
    content_length = int(self.headers['Content-Length']) # <--- Gets the size of data
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

If I add `Content-Length` header manually, server does not show this exception, but drill will show timeout error like this.
```
Error connecting 'http://127.0.0.1:3000/items/ITEM-ID-1': reqwest::Error { kind: Request, url: "http://127.0.0.1:3000/items/ITEM-ID-1", source: TimedOut }
```

I think the commit ( https://github.com/fcsonline/drill/commit/4ad7822ae40f1c8f4b964dec212117ec6c868240 ) made this change, `body` is allowed for the `POST` method only.

**Comment by fcsonline** [comment]
I just pushed this branch to fix this. Can you give it a try?

https://github.com/fcsonline/drill/pull/85

**Comment by yoshihitoh** [comment]
Thank you, `PATCH` and `PUT` worked well on the `feature/body-patch` branch! I used this template.

<details>
<summary>test.yaml</summary>
<p>
```
---
concurrency: max
iterations: 1

plan:
    - name: Assign access token
      assign:
        key: access_token
        value: MY-ACCESS-TOKEN-HERE

    - name: Test PATCH
      request:
        url: http://127.0.0.1:3000/items/{{ item }}
        method: PATCH
        body: '{"params": {"name": "NAME"} }'
        headers:
          Authorization: Bearer {{ access_token }}
          Content-Type: application/json
      with_items:
        - "ITEM-ID-1"
        - "ITEM-ID-2"

    - name: Test PUT
      request:
        url: http://127.0.0.1:3000/items/{{ item }}
        method: PUT
        body: '{"params": {"name": "NAME"} }'
        headers:
          Authorization: Bearer {{ access_token }}
          Content-Type: application/json
      with_items:
        - "ITEM-ID-1"
        - "ITEM-ID-2"
```
</p>
<details>

**Comment by fcsonline** [comment]
Closing issue. Feel free to open it again if something is now working as expected.
